name: Run Gradle on PRs
on:
  pull_request:
  push:
  workflow_dispatch:
jobs:
  gradle:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ghidra:
        - "11.2"
        - "11.2.1"
    
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'
    - uses: antoniovazquezblanco/setup-ghidra@v2.0.5
      with:
        auth_token: ${{ secrets.GITHUB_TOKEN }}
        version: ${{ matrix.ghidra }}
    - name: Build targetting Ghidra ${{ matrix.ghidra }}
      run: ./gradlew -PGHIDRA_INSTALL_DIR=${{ env.GHIDRA_INSTALL_DIR }}
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          ./dist/GameCubeLoader-*.zip
